### ISSUE TITLE
@org of "choice" on <attList> has no effect in a class specification

### ISSUE THREAD

**Issue by sydb** [TEIC/Stylesheets#144]
I added `<attList org="choice">` to att.datable.w3c, but it seems to have no effect. We use it in several places which work just fine:
- relation: works (but has Schematron as well) 
- classRef: works
- moduleRef: both work
- dataRef: works

But I note that these are all in elementSpecs, whereas this new use is within a classSpec. It's possible I'm just doing something wrong. The structure I put in is:

``` xml
  <attList org="choice">
    <attDef ident="when" usage="opt">
    <attList org="group">
      <attDef ident="notBefore" usage="opt">
      <attDef ident="notAfter" usage="opt">
      <attDef ident="from" usage="opt">
      <attDef ident="to" usage="opt">
    </attList>
  </attList>
```

**Comment by lb42** [comment]
I don't think you can use @org=choice like this. It's meant to give you a choice between attDefs, not a choice between an attDef and an attList. in the pure ODD world, of course, we should probably use &lt;alternate> but that's not implemented either. If what you're saying is "either @when is available or all the others are available", that's best expressed in schematron at present., as Hugh suggests.

**Comment by sydb** [comment]
I infer from the Guidelines (22.5.4 and the tagdoc for `<attList>`) that `@org=choice` is supposed to work **exactly** like that. That said, I can see how someone else might read that section to imply that `<attList>` is not supposed to be a child of `<attList org=choice>`. But if that is what we meant, why didn’t we say so? Why didn’t we add a Schematron check to enforce it?

So my take is that it is stylesheets that are in error. (And now that I think about it I have a vague recollection that this has came up years ago, and Sebastian conceded that the stylesheets were in error, but had no intentions of fixing this bug. But I’m not at all sure of that.)

In any case, it seems pretty clear it *doesn’t* work that way. So the solution for now is to not use that construct, and then discuss its future (or that of its PureODD equivalent, `<alternate>`). For the moment it seems as the Council is having second thoughts, if not a complete turn-around, about the wisdom of the constraint itself, anyway.

Sigh.

**Comment by hcayless** [comment]
It's the first I'm hearing of it and I don't have an opinion yet. It might turn out to be hard to implement or it might not. On the face of it, it doesn't seem like a bad idea.

**Comment by bansp** [comment]
The [issue that I had and @sydb kindly addressed at TEI-L](http://tei-l.970651.n3.nabble.com/can-pure-ODD-define-an-alternation-of-attribute-patterns-td4029511.html) would be a case for 
```xml
<attList org="choice">
    <attList org="group">...</attList>
    <attList org="group">...</attList>
    <attList org="group">...</attList>
</attList>
```
Whoa, that would be so exciting to have! Of course, it would also be completely contrary to the expectation that @lb42 mentioned above (that it's only attDefs that can get handled in such a way). I'd love a world in which this expectation were not fulfilled... :-)

**Comment by martindholmes** [comment]
@ebeshero and I suggest first confirming that this still exists, and then deciding whether it's actually a TEI ticket first.

**Comment by JanelleJenstad** [comment]
@sydb and I decided to close this ticket and make a new TEI ticket. See TEIC/TEI#2136

**Comment by sydb** [comment]
Council decides to continue to use `org="choice"`, so re-opened, as it needs to work in the classSpec case.

**Comment by sydb** [comment]
While working on TEIC/TEI#2653 , I found another case where `org="choice"` fails to work within a class. (I.e., I tried putting `org="choice"` on the `<attList>` in att.edition.xml, and it did not change the output RELAX NG.)
