### ISSUE TITLE
constraintSpec inside attDef output is both ugly and wrong

### ISSUE THREAD

**Issue by sydb** [TEIC/Stylesheets#482]
We have only two elements which have a `<constraintSpec>` inside an `<attDef>`: `<moduleRef>` and `<variantEncoding>`. (We have lots of attribute classes that sport an `<constraintSpec>` inside an `<attDef>`, but they are not problematic, because the “Schema Declaration” is not displayed on their tagdocs. Not sure why not.)

In both cases a large chunk of the “Schema Declaration” of the HTML output (and probably PDF and ePub, but notably **not** the output RELAX NG) looks awful. On slightly closer examination, it not only looks awful, it does not correctly represent the Schematron. Not even close. (Well, maybe you could call it close — in some sense it represents the `<constraint>` itself, I think.)

**Comment by martindholmes** [comment]
Wow, that does look bad:

https://tei-c.org/release/doc/tei-p5-doc/en/html/ref-moduleRef.html

This seems like it shouldn't be too difficult to fix. The Schematron seems nicely-laid-out in the attribute definition itself, it's just that it shows up all borked in the schema declaration. This should be release-blocking.

**Comment by sydb** [comment]
I do not think it makes sense to make this release-blocking: it has been around since 2.8.0 was released in April 2015, and no one has complained until now. I am pretty confident that the borking (as you put it, @martindholmes) has to do with the fact that the XML `<constraint>` is converted somehow to an XHTML `<tr>` before being handed to `trang` to be converted to compact syntax.

**Comment by martindholmes** [comment]
@sydb Idon't think the fact that something has been around for a long time should have any bearing on whether it's release-blocking. If it's egregious and fixable it should be fixed before the next release, no?

**Comment by sydb** [comment]
Sure, it _should_ be fixed before the next release. But I don’t think the next release should be delayed or canceled if, perchance, it is not fixed in time.

**Comment by hcayless** [comment]
What, precisely, are you complaining about here? We're looking at this in the Stylesheets group and are thoroughly confused...

**Comment by martindholmes** [comment]
Looks like this was fixed between 4.2.0 and 4.2.1 -- look at the bottom of this page and you'll see the original problem:

https://tei-c.org/Vault/P5/4.2.0/doc/tei-p5-doc/en/html/ref-moduleRef.html

Should be OK to close it now, though.

**Comment by martinascholger** [comment]
True, that was one reason for the 4.2.1 release. Closing the issue.
